version: '2.1'

services:

  cli:
    extends:
      service: yo
    working_dir: /usr/local/lib/node_modules/generator-pattern-lab-starter
    entrypoint: ["/usr/bin/env"]
    command: "bash"

  yo:
    image: outrigger/yeoman
    network_mode: "bridge"
    volumes:
      - ${YO_PROJECT_DIRECTORY:-~/Projects/newproject}:/generated
      - .:/usr/local/lib/node_modules/generator-pattern-lab-starter:ro
